// import {
//     MatDatepickerModule,
//     MatNativeDateModule,
//     MatFormFieldModule,
//     MatInputModule,
//     MatPaginatorModule,
//     MatTableModule,
//     MatSelectModule,
//     MatCheckboxModule,
//     MatExpansionModule,
//     MatMenuModule,
//     MatCardModule,
//     MatRadioModule,
//     MatAutocompleteModule,
//     MatChipsModule,
//     MatIconModule,
//     MatTabsModule,
//     MatTooltipModule,
//     MatProgressSpinnerModule,
//     MatToolbarModule,
//     MatSortModule,
//     MatDialogModule,
//     MatSliderModule,
//     MatSlideToggleModule,
//     MatSnackBarModule
//   } from '@angular/material';

// export const modules: any = [
//     MatDatepickerModule,
//     MatNativeDateModule,
//     MatFormFieldModule,
//     MatInputModule,
//     MatTableModule,
//     MatPaginatorModule,
//     MatSelectModule,
//     MatCheckboxModule,
//     MatExpansionModule,
//     MatMenuModule,
//     MatCardModule,
//     MatRadioModule,
//     MatAutocompleteModule,
//     MatChipsModule,
//     MatIconModule,
//     MatTabsModule,
//     MatTooltipModule,
//     MatProgressSpinnerModule,
//     MatToolbarModule,
//     MatSortModule,
//     MatDialogModule,
//     MatSliderModule,
//     MatSlideToggleModule,
//     MatSnackBarModule
// ];

export const modules: any = [];
